// 'use client';

import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';
import { useDispatch, useSelector } from 'react-redux';
import { logout } from '../services/features/auth/authSlice';
import { getUsers } from '../services/features/users/usersSlice';
import { useEffect } from 'react';
import { AppDispatch } from '../services/store';
import Link from 'next/link';
import RoomAside from '../components/RoomAside';
import AsideMobileUsers from '../components/mobile/Users';
import AsideUsers from '../components/AsideUsers';
import { MdMessage } from 'react-icons/md';
import { toast } from 'react-toastify';

export default function Home() {
	const router = useRouter();
	const dispatch = useDispatch<AppDispatch>();
	const {
		user,
		isError: isErrorUser,
		errorMessage: errorUser,
	} = useSelector((state: any) => state.auth);
	const { isError: isErrorMessages, errorMessage: errorMessages } = useSelector(
		(state: any) => state.messages
	);

	const { isError: isErrorUsers, errorMessage: errorUsers } = useSelector(
		(state: any) => state.users
	);

	useEffect(() => {
		if (!user) router.push('/auth/login');
		if (user) dispatch(getUsers());
	}, [user, dispatch]);

	useEffect(() => {
		if (isErrorMessages) toast.dark(errorMessages);
		if (isErrorUser) toast.dark(errorUser);
		if (isErrorUsers) toast.error(errorUsers);
	}, [isErrorMessages, isErrorUser]);

	return (
		<>
			<div className={styles.container}>
				<Head>
					<title>Crypto chat</title>
					<meta name='description' content='Generated by create next app' />
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<main className='flex fixed top-0 bottom-0 left-0 right-0 bg-blue-900 '>
					<RoomAside />

					{/* aside for users */}
					<AsideUsers />
					<AsideMobileUsers />

					{/* Main messages */}
					<div className='hidden sm:flex top-2 bottom-2 left-20 w-full bg-gray-900 rounded-xl p-4 mx-2 my-2 flex-col items-center justify-center text-center'>
						{user && (
							<>
								<h2 className='text-3xl text-slate-100 font-extrabold m-2'>
									Welcome{' '}
									<span className='text-blue-900'>{user && user?.name}</span>{' '}
									<span className='text-blue-900'>
										{user && user?.lastname}
									</span>
								</h2>
								<p className='text-slate-50'>
									Select please one contact to start a chat{' '}
								</p>
								<h5 className='text-8xl text-white animate-pulse mt-5'>
									<MdMessage />
								</h5>
							</>
						)}
					</div>
				</main>
			</div>
			<AsideUsers />
		</>
	);
}
